research_task:
  description: >
    Conduct an initial analysis on {image_path}. Identify details such as:
    - Image quality
    - Subject matter
    - Key features
  expected_output: >
    A summary of key details from the image.
  agent: image_researcher

inspection_task:
  description: >
    Perform a detailed quality inspection on {image_path}. Focus on:
    1. Image sharpness and clarity
    2. Lighting conditions
    3. Any visible defects
  expected_output: >
    A report highlighting any detected issues in the image.
  agent: expert_analyst

reporting_task:
  description: >
    Summarize findings from previous tasks into a structured report.
  expected_output: >
    A well-structured markdown report containing all image insights.
  agent: reporting_analyst
